<h2>Sign using this form</h2>

<?php $this->flashSession->output(); ?>

<?php echo $this->tag->form('signup/register') ?>

	<p>
		<label for="name">Name</label>
		<?php echo $this->tag->textField("name") ?>
	</p>

	<p>
		<label for="name">E-Mail</label>
		<?php echo $this->tag->textField("email") ?>
	</p>

	<p>
		<label for="password">Password</label>
		<?php echo $this->tag->textField("password") ?>
	</p>

	<p>
		<?php echo $this->tag->submitButton("Register") ?>
	</p>

</form>
